services:
  app:
    container_name: nginx
    image: nginx:1.28.0-alpine3.21-slim
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./conf:/etc/nginx/conf.d:ro
      - ./data:/var/www:ro
      - ./logs:/var/log/nginx:rw

networks:
  default:
    name: web
    external: true

