services:
  app:
    image: ilmuflone/muflone-rendered:2024-11-08.4
    networks:
      - public
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /opt/certbot-data/live/muflone.com/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - /opt/certbot-data/live/muflone.com/cert.pem:/etc/nginx/ssl/cert.pem:ro
      - /opt/certbot-data/live/muflone.com/chain.pem:/etc/nginx/ssl/chain.pem:ro
      - /opt/certbot-data/live/muflone.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
    secrets:
      - nginx_dhparam.pem

networks:
  public:
    external: true

secrets:
  nginx_dhparam.pem:
    external: true

