services:
  app:
    image: nginx:1.25.4-alpine3.18-slim
    networks:
      - public
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - conf:/etc/nginx/conf.d:rw
      - data:/var/www:rw
      - logs:/var/log/nginx:rw
      - /opt/certbot-data/live/muflone.com/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - /opt/certbot-data/live/muflone.com/cert.pem:/etc/nginx/ssl/cert.pem:ro
      - /opt/certbot-data/live/muflone.com/chain.pem:/etc/nginx/ssl/chain.pem:ro
      - /opt/certbot-data/live/muflone.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro

networks:
  public:
    external: true

volumes:
  conf:

  data:

  logs:

