services:
  app:
    container_name: nginx
    image: nginx:1.27.3-alpine3.20-slim
    restart: unless-stopped
    networks:
      - public
    volumes:
      - ./conf:/etc/nginx/conf.d:ro
      - ./data:/var/www:ro
      - ./logs:/var/log/nginx:rw

networks:
  public:
    external: true

